spring:
  application.name: pallas
  r2dbc:
    url: r2dbc:postgresql://localhost:5432/postgres
    username: postgres
    password: postgres
#  datasource:
#    url: jdbc:postgresql://localhost:5432/postgres
#    username: postgres
#    password: postgres
  liquibase:
    url: jdbc:postgresql://localhost:5432/postgres
    password: postgres
    user: postgres
server:
  port: 8082